In [7]:
import pandas as pd
import sqlite3

In [9]:
orders = pd.read_csv("orders.csv")
orders.head()

,order_id,user_id,restaurant_id,order_date,total_amount,restaurant_name
0,1,2508,450,18-02-2023,842.97,New Foods Chinese
1,2,2693,309,18-01-2023,546.68,Ruchi Curry House Multicuisine
2,3,2084,107,15-07-2023,163.93,Spice Kitchen Punjabi
3,4,319,224,04-10-2023,1155.97,Darbar Kitchen Non-Veg
4,5,1064,293,25-12-2023,1321.91,Royal Eatery South Indian

In [11]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         10000 non-null  int64
 1   user_id          10000 non-null  int64
 2   restaurant_id    10000 non-null  int64
 3   order_date       10000 non-null  object
 4   total_amount     10000 non-null  float64
 5   restaurant_name  10000 non-null  object
dtypes: float64(1), int64(3), object(2)
memory usage: 468.9+ KB

In [13]:
users = pd.read_json("users.json")

In [17]:
users.head()

   user_id    name       city membership
0        1  User_1    Chennai    Regular
1        2  User_2       Pune       Gold
2        3  User_3  Bangalore       Gold
3        4  User_4  Bangalore    Regular
4        5  User_5       Pune       Gold

In [19]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     3000 non-null   int64
 1   name        3000 non-null   object
 2   city        3000 non-null   object
 3   membership  3000 non-null   object
dtypes: int64(1), object(3)
memory usage: 93.9+ KB

In [21]:
conn = sqlite3.connect("restaurants.db")

In [25]:
import sqlite3
conn = sqlite3.connect("restaurants.db")

In [35]:
pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)

Empty DataFrame
Columns: [name]
Index: []

In [37]:
with open("restaurants.sql", "r") as f:
    sql_script = f.read()

In [40]:
conn = sqlite3.connect("restaurants.db")
conn.executescript(sql_script)

In [42]:
pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)

          name
0  restaurants

In [44]:
restaurants = pd.read_sql_query(
    "SELECT * FROM restaurants",
    conn
)

In [46]:
conn.close()

In [50]:
restaurants.head()

   restaurant_id restaurant_name  cuisine  rating
0              1    Restaurant_1  Chinese     4.8
1              2    Restaurant_2   Indian     4.1
2              3    Restaurant_3  Mexican     4.3
3              4    Restaurant_4  Chinese     4.1
4              5    Restaurant_5  Chinese     4.8

In [52]:
restaurants.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   restaurant_id    500 non-null    int64
 1   restaurant_name  500 non-null    object
 2   cuisine          500 non-null    object
 3   rating           500 non-null    float64
dtypes: float64(1), int64(1), object(2)
memory usage: 15.8+ KB

In [54]:
orders_users = pd.merge(
    orders,
    users,
    on="user_id",
    how="left"
)

In [56]:
orders_users.shape
orders_users.head()

,order_id,user_id,restaurant_id,order_date,total_amount,restaurant_name,name,city,membership
0,1,2508,450,18-02-2023,842.97,New Foods Chinese,User_2508,Hyderabad,Regular
1,2,2693,309,18-01-2023,546.68,Ruchi Curry House Multicuisine,User_2693,Pune,Regular
2,3,2084,107,15-07-2023,163.93,Spice Kitchen Punjabi,User_2084,Chennai,Gold
3,4,319,224,04-10-2023,1155.97,Darbar Kitchen Non-Veg,User_319,Bangalore,Gold
4,5,1064,293,25-12-2023,1321.91,Royal Eatery South Indian,User_1064,Pune,Regular

In [58]:
final_df = pd.merge(
    orders_users,
    restaurants,
    on="restaurant_id",
    how="left"
)

In [60]:
final_df.shape
final_df.head()
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   order_id           10000 non-null  int64
 1   user_id            10000 non-null  int64
 2   restaurant_id      10000 non-null  int64
 3   order_date         10000 non-null  object
 4   total_amount       10000 non-null  float64
 5   restaurant_name_x  10000 non-null  object
 6   name               10000 non-null  object
 7   city               10000 non-null  object
 8   membership         10000 non-null  object
 9   restaurant_name_y  10000 non-null  object
 10  cuisine            10000 non-null  object
 11  rating             10000 non-null  float64
dtypes: float64(2), int64(3), object(7)
memory usage: 937.6+ KB

In [62]:
final_df.isnull().sum()

order_id             0
user_id              0
restaurant_id        0
order_date           0
total_amount         0
restaurant_name_x    0
name                 0
city                 0
membership           0
restaurant_name_y    0
cuisine              0
rating               0
dtype: int64

In [66]:
final_df["membership"] = final_df["membership"].fillna("Unknown")

In [68]:
final_df.to_csv(
    "final_food_delivery_dataset.csv",
    index=False
)

In [70]:
final_df = pd.read_csv("final_food_delivery_dataset.csv")

In [76]:
final_df["order_date"] = pd.to_datetime(
    final_df["order_date"],
    dayfirst=True
)

In [78]:

final_df.head()
final_df.shape

(10000, 12)

In [80]:
final_df["order_date"] = pd.to_datetime(final_df["order_date"])

orders_over_time = final_df.groupby(final_df["order_date"].dt.date).size()
orders_over_time.head()

order_date
2023-01-01    29
2023-01-02    19
2023-01-03    35
2023-01-04    26
2023-01-05    25
dtype: int64

In [82]:
orders_per_user = final_df.groupby("user_id")["order_id"].count()
orders_per_user.describe()

count    2883.000000
mean        3.468609
std         1.792682
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max        13.000000
Name: order_id, dtype: float64

In [84]:
final_df.groupby("user_id")["total_amount"].sum().sort_values(ascending=False).head(10)

user_id
1515    11556.49
650     10747.44
496      9634.30
2586     9486.61
2615     9237.32
636      9087.09
2973     9063.07
874      8916.55
1337     8907.50
2694     8875.71
Name: total_amount, dtype: float64

In [86]:
city_revenue = final_df.groupby("city")["total_amount"].sum().sort_values(ascending=False)
city_revenue

city
Bangalore    2206946.58
Chennai      1990513.03
Pune         1924797.93
Hyderabad    1889366.58
Name: total_amount, dtype: float64

In [88]:
cuisine_orders = final_df.groupby("cuisine")["order_id"].count().sort_values(ascending=False)
cuisine_orders

cuisine
Mexican    2581
Italian    2532
Indian     2469
Chinese    2418
Name: order_id, dtype: int64

In [90]:
final_df.groupby("cuisine")["total_amount"].sum().sort_values(ascending=False)

cuisine
Mexican    2085503.09
Italian    2024203.80
Indian     1971412.58
Chinese    1930504.65
Name: total_amount, dtype: float64

In [92]:
membership_analysis = final_df.groupby("membership")["total_amount"].agg(["count", "sum", "mean"])
membership_analysis

            count         sum        mean
membership
Gold         4987  3975364.89  797.145556
Regular      5013  4036259.23  805.158434

In [94]:
final_df["total_amount"].describe()

count    10000.000000
mean       801.162412
std        405.458753
min        100.200000
25%        446.310000
50%        806.295000
75%       1149.227500
max       1499.830000
Name: total_amount, dtype: float64

In [98]:
final_df.columns

Index(['order_id', 'user_id', 'restaurant_id', 'order_date', 'total_amount',
       'restaurant_name_x', 'name', 'city', 'membership', 'restaurant_name_y',
       'cuisine', 'rating'],
      dtype='object')

In [101]:
final_df.groupby("restaurant_name_y")["total_amount"] \
        .sum() \
        .sort_values(ascending=False) \
        .head(10)

restaurant_name_y
Restaurant_287    29460.47
Restaurant_19     29289.52
Restaurant_484    27051.49
Restaurant_61     26049.71
Restaurant_134    25791.23
Restaurant_440    25467.45
Restaurant_383    24955.59
Restaurant_188    24698.82
Restaurant_431    24684.31
Restaurant_153    24523.66
Name: total_amount, dtype: float64

In [103]:
# If restaurant name column is 'name'
final_df.rename(columns={"name": "restaurant_name"}, inplace=True)

# If you still have duplicate columns, remove them
final_df.drop(columns=[col for col in final_df.columns if col.endswith("_x")], inplace=True)

In [105]:
final_df.columns

Index(['order_id', 'user_id', 'restaurant_id', 'order_date', 'total_amount',
       'restaurant_name', 'city', 'membership', 'restaurant_name_y', 'cuisine',
       'rating'],
      dtype='object')

In [107]:
final_df["order_date"] = pd.to_datetime(final_df["order_date"], format="%d-%m-%Y")

In [109]:
final_df[final_df["membership"] == "Gold"] \
    .groupby("city")["total_amount"] \
    .sum() \
    .sort_values(ascending=False)

city
Chennai      1080909.79
Pune         1003012.32
Bangalore     994702.59
Hyderabad     896740.19
Name: total_amount, dtype: float64

In [111]:
final_df.groupby("cuisine")["total_amount"].mean().sort_values(ascending=False)

cuisine
Mexican    808.021344
Italian    799.448578
Indian     798.466011
Chinese    798.389020
Name: total_amount, dtype: float64

In [113]:
high_value_users = final_df.groupby("user_id")["total_amount"].sum()
(high_value_users > 1000).sum()

2544

In [115]:
bins = [3.0, 3.5, 4.0, 4.5, 5.0]
labels = ["3.0–3.5", "3.6–4.0", "4.1–4.5", "4.6–5.0"]

final_df["rating_range"] = pd.cut(final_df["rating"], bins=bins, labels=labels)

final_df.groupby("rating_range")["total_amount"].sum().sort_values(ascending=False)

C:\Users\Gayatri\AppData\Local\Temp\ipykernel_28016\3081351284.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  final_df.groupby("rating_range")["total_amount"].sum().sort_values(ascending=False)

rating_range
4.6–5.0    2197030.75
4.1–4.5    1960326.26
3.0–3.5    1881754.57
3.6–4.0    1717494.41
Name: total_amount, dtype: float64

In [117]:
final_df[final_df["membership"] == "Gold"] \
    .groupby("city")["total_amount"] \
    .mean() \
    .sort_values(ascending=False)

city
Chennai      808.459080
Hyderabad    806.421034
Bangalore    793.223756
Pune         781.162243
Name: total_amount, dtype: float64

In [119]:
restaurant_count = final_df.groupby("cuisine")["restaurant_name"].nunique()
revenue = final_df.groupby("cuisine")["total_amount"].sum()

pd.concat([restaurant_count, revenue], axis=1)

         restaurant_name  total_amount
cuisine
Chinese             1635    1930504.65
Indian              1679    1971412.58
Italian             1701    2024203.80
Mexican             1719    2085503.09

In [121]:
gold_orders = final_df[final_df["membership"] == "Gold"].shape[0]
total_orders = final_df.shape[0]

round((gold_orders / total_orders) * 100)

50

In [123]:
restaurant_stats = final_df.groupby("restaurant_name")["total_amount"] \
    .agg(["count", "mean"])

restaurant_stats[restaurant_stats["count"] < 20] \
    .sort_values("mean", ascending=False) \
    .head()

                 count     mean
restaurant_name
User_2429            1  1497.42
User_889             1  1492.63
User_1843            1  1484.24
User_1882            1  1481.84
User_925             1  1476.18

In [125]:
final_df["quarter"] = final_df["order_date"].dt.to_period("Q")

final_df.groupby("quarter")["total_amount"].sum().sort_values(ascending=False)

quarter
2023Q3    2037385.10
2023Q4    2018263.66
2023Q1    1993425.14
2023Q2    1945348.72
2024Q1      17201.50
Freq: Q-DEC, Name: total_amount, dtype: float64

In [127]:
final_df.groupby(["membership", "cuisine"])["total_amount"] \
    .sum() \
    .sort_values(ascending=False)

membership  cuisine
Regular     Mexican    1072943.30
            Italian    1018424.75
Gold        Mexican    1012559.79
            Italian    1005779.05
Regular     Indian      992100.27
Gold        Indian      979312.31
            Chinese     977713.74
Regular     Chinese     952790.91
Name: total_amount, dtype: float64

In [129]:
# How many total orders were placed by Gold members?
gold_orders = final_df[final_df["membership"] == "Gold"]
gold_orders.shape[0]

4987

In [131]:
# Total revenue from Hyderabad (rounded)
hyd_revenue = final_df[final_df["city"] == "Hyderabad"]["total_amount"].sum()
round(hyd_revenue)

1889367

In [133]:
#How many distinct users placed at least one order?
final_df["user_id"].nunique()

2883

In [135]:
#What is the average order value (rounded to 2 decimals) for Gold members?
round(
    final_df[final_df["membership"] == "Gold"]["total_amount"].mean(),
    2
)

797.15

In [137]:
#How many orders were placed for restaurants with rating ≥ 4.5?
final_df[final_df["rating"] >= 4.5].shape[0]

3374

In [141]:
#How many orders were placed in the top revenue city among Gold members only?
top_city = (
    final_df[final_df["membership"] == "Gold"]
    .groupby("city")["total_amount"]
    .sum()
    .idxmax()
)
top_city

final_df[
    (final_df["membership"] == "Gold") &
    (final_df["city"] == top_city)
].shape[0]

1337